# Development Dockerfile for ROS2 with Nvidia GPU support
# Maintainer: Dayuan
services:
  theta_ros2:
    container_name: theta_ros2
    image: theta_ros2
    build: ./
    volumes:
      - ./packages:/src/
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/:/dev/ # Little bit dangerous, but it works
    working_dir: /ros2_ws
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
   
    network_mode: "host"  # Must with this line to enable display
    ipc: host
    privileged: true
    stdin_open: true
